import { chromium } from 'playwright';
const b=await chromium.launch({headless:true}); const p=await b.newPage();
const logs=[]; const errs=[];
p.on('console', m=>{ if(m.type()==='warning' && m.text().includes('BADDATA')) logs.push(m.text()); });
p.on('pageerror', e=>errs.push(e.message));
await p.goto("http://127.0.0.1:5501/",{waitUntil:"domcontentloaded",timeout:20000});
await p.waitForTimeout(5000);
console.log("=== AFTER INITIAL LOAD ===");
console.log("pageerrors:", errs.length);
console.log("baddata logs:", logs.length);
logs.forEach(l=>console.log(l));
logs.length=0; errs.length=0;
await p.evaluate(()=>{ activeSymbol='BTC-USD'; activeTF='1h'; loadChart('BTC-USD','1h'); });
await p.waitForTimeout(6000);
console.log("=== AFTER BTC-USD 1h SWITCH ===");
console.log("pageerrors:", errs.length);
console.log("baddata logs:", logs.length);
logs.forEach(l=>console.log(l));
await b.close();
