// Asset catalog — ported from Reach's src/data/assetCatalog.js.
//
// Reach resolves an asset's colour and logo on demand from its symbol + the asset type (the active
// tab), rather than storing either on the catalog entry. Kept that way here.
//
// The four metals use Reach's bundled animated coin .gifs, copied to /public/metals. Reach imports
// them through Vite under their original Tibia sprite names, with a mapping that is *not* the
// obvious one — its XAG points at Platinum_Coin.gif and its XPT at Crystal_Coin.gif (the Tibia
// platinum coin reads as silver, the crystal coin as platinum). That indirection is resolved here
// at the filename: each file is named for the metal it depicts, so the code below stays literal.
//
// `metalSvg()` is kept as the fallback for any metal without artwork.

export type AssetType = 'crypto' | 'stock' | 'metal' | 'currency';

export interface CatalogAsset {
  symbol: string;
  name: string;
}

// ── Brand colours ──
const BRAND_COLORS: Record<string, string> = {
  // Crypto
  BTC: '#f7931a', ETH: '#627eea', BNB: '#f3ba2f', XRP: '#23292f',
  SOL: '#9945FF', DOGE: '#c2a633', ADA: '#0033AD', TRX: '#EF0027',
  LINK: '#375BD2', XLM: '#000000', LTC: '#bfbbbb', AVAX: '#e84142',
  SHIB: '#fda32b', DOT: '#e6007a', UNI: '#FF007A', ATOM: '#2E3148',
  NEAR: '#000000', ETC: '#328332', ICP: '#29abe2', FIL: '#0090ff',
  HBAR: '#000000', APT: '#4cd080', ARB: '#28a0f0', OP: '#ff0420',
  VET: '#15bdff', ALGO: '#000000', AAVE: '#b6509e', INJ: '#00f2fe',
  MATIC: '#8247e5', SEI: '#9B1B30',
  MKR: '#1aab9b', GRT: '#6747ED', RNDR: '#000000', SUI: '#4da2ff',
  TON: '#0098EA', PEPE: '#4b8b3b', THETA: '#2ab8e6', SAND: '#04adef',
  MANA: '#ff2d55', AXS: '#0055d5', ENJ: '#624dbf', BAT: '#ff5000',
  ZEC: '#f4b728', XMR: '#ff6600', DASH: '#008ce7', NEO: '#00e599',
  COMP: '#00d395', SNX: '#170659', CRV: '#a2a2a2', FTM: '#1969ff',
  CAKE: '#d1884f', GALA: '#000000', APE: '#0054f9', RUNE: '#33ff99',
  DYDX: '#6966ff', FLOW: '#00ef8b', KAVA: '#ff564f', EOS: '#000000',
  BCH: '#8dc351', PAXG: '#e4ce4d', YFI: '#006ae3', SUSHI: '#d65892',
  UMA: '#ff4a4a', BAL: '#1e1e1e',
  // Stablecoins
  USDT: '#26a17b', USDC: '#2775ca', DAI: '#f5ac37', TUSD: '#002868',
  // Stocks
  AAPL: '#555555', MSFT: '#00a4ef', GOOGL: '#4285f4', AMZN: '#ff9900',
  TSLA: '#cc0000', META: '#0668e1', NVDA: '#76b900', JPM: '#004b8d',
  V: '#1a1f71', MA: '#eb001b', NFLX: '#e50914', DIS: '#0050aa',
  AMD: '#ed1c24', INTC: '#0071c5', WMT: '#0071dc', BA: '#0033a0',
  GS: '#6f9fd8', CRM: '#00a1e0', ADBE: '#ff0000', NKE: '#111111',
  KO: '#f40000', PYPL: '#003087', COIN: '#0052ff', PLTR: '#101010',
  // Metals
  XAU: '#FFD700', XAG: '#C0C0C0', XPT: '#e5e4e2', XPD: '#CED0DD',
  // Currencies
  EUR: '#003399', GBP: '#012169', JPY: '#bc002d', MXN: '#006847',
  CAD: '#ff0000', AUD: '#00008b', CHF: '#d52b1e', CNY: '#de2910',
  BRL: '#009b3a', KRW: '#003478',
};

/** Deterministic fallback colour for symbols with no brand entry. */
function hashColor(sym: string): string {
  let h = 0;
  for (const c of sym) h = c.charCodeAt(0) + ((h << 5) - h);
  return `hsl(${Math.abs(h) % 360}, 55%, 50%)`;
}

// ── Crypto identity colours, measured from the actual logos ──
//
// The allocation donut, chip backgrounds and legend dots all colour by getAssetColor. BRAND_COLORS
// carries several literal brand blacks (NEAR, XLM, HBAR, ALGO…) that are invisible against the dark
// UI — a 100%-NEAR portfolio drew a black donut. Each entry below is the logo's dominant colour,
// computed per PNG (saturation-weighted mean of opaque pixels, lightness clamped to the visible
// range); visibly-bright brand entries are kept verbatim, near-black brands are replaced by the
// measured colour (NEAR → its logo's green), and genuinely monochrome logos get a neutral gray
// rather than an invented hue. Generated by scratchpad/gen-colors.mjs alongside the logo audit.
const CRYPTO_ICON_COLORS: Record<string, string> = {
  ETH: '#627eea', BTC: '#f7931a', SOL: '#9945ff', XRP: '#23292f', TRX: '#ef0027', ADA: '#0033ad',
  DOGE: '#c2a633', LINK: '#375bd2', BNB: '#f3ba2f', XLM: '#8a919c', LTC: '#bfbbbb', AVAX: '#e84142',
  DOT: '#e6007a', UNI: '#ff007a', ATOM: '#2e3148', FIL: '#0090ff', ETC: '#328332', ICP: '#29abe2',
  MATIC: '#8247e5', VET: '#15bdff', ALGO: '#078bcf', QNT: '#8a919c', AAVE: '#b6509e', HBAR: '#8a919c',
  NEAR: '#01d88a', CHZ: '#ff1357', STX: '#fc6736', ARB: '#28a0f0', INJ: '#00f2fe', CRV: '#a2a2a2',
  GRT: '#6747ed', MKR: '#1aab9b', IMX: '#8a919c', OP: '#ff0420', SUI: '#4da2ff', PEPE: '#4b8b3b',
  TON: '#0098ea', ONDO: '#8a919c', APT: '#4cd080', BONK: '#ee9f0b', WLD: '#8a919c', THETA: '#2ab8e6',
  SHIB: '#fda32b', PENGU: '#8ab2e5', ENJ: '#624dbf', KAS: '#70c9bb', FLOKI: '#f19928', SEI: '#9b1b30',
  TAO: '#8a919c', ZEC: '#f4b728', BAT: '#ff5000', DASH: '#008ce7', XMR: '#ff6600', WAVES: '#0054ff',
  NEO: '#00e599', ZIL: '#2ca2aa', SAND: '#04adef', MANA: '#ff2d55', COMP: '#00d395', JUP: '#3b9b8c',
  SNX: '#170659', FET: '#8a919c', ONT: '#49a4ff', ZRX: '#8a919c', ONE: '#3bdad8', KNC: '#33cb99',
  RNDR: '#d11b1c', BAND: '#7070ff', STORJ: '#2685ff', NMR: '#8a919c', LRC: '#1d61ff', OXT: '#6045bb',
  SKL: '#8a919c', ANKR: '#356df3', RSR: '#0163d5', AXS: '#0055d5', GALA: '#8a919c', IOST: '#8a919c',
  APE: '#0054f9', GMT: '#e4ba7a', ICX: '#34bbcf', OMG: '#8a919c', CELO: '#f2f450', SC: '#ba9549',
  QTUM: '#0745f7', DYDX: '#6966ff', ZEN: '#bd9a1a', MASK: '#1c68f3', FLOW: '#00ef8b', MINA: '#c76ac5',
  ROSE: '#0b06e3', RUNE: '#33ff99', EOS: '#ff8331', JASMY: '#f8a544', CAKE: '#d1884f', IOTX: '#8a919c',
  AUDIO: '#980fc7', KAVA: '#ff564f', AR: '#8a919c', SXP: '#f64a28', BAL: '#8a919c', EGLD: '#22f0d7',
  YFI: '#006ae3', SUSHI: '#d65892', LDO: '#d89c97', BNT: '#25c2ca', UMA: '#ff4a4a', REN: '#2165b5',
  FTM: '#1969ff', FUN: '#d5195e', RPL: '#ffaa70', ACH: '#0a1dcc', MTL: '#8a919c', DENT: '#e13228',
  REQ: '#07cf89', CELR: '#8a919c', RLC: '#f9cf5a', SYS: '#1f5eff', BLZ: '#7072ff', ALICE: '#ea858c',
  SUPER: '#71f194', LINA: '#5480fc', CVC: '#8a919c', NKN: '#364ea1', CTSI: '#00f5fe', TLM: '#8a919c',
  COTI: '#5686c4', OGN: '#0174f0', FLUX: '#3064d2', FXS: '#8a919c', RVN: '#3c489e', AGLD: '#8a919c',
  PEOPLE: '#a57e3f', BCH: '#8dc351', HIGH: '#17a0ef', XVS: '#2d77c2', PAXG: '#e4ce4d', RAD: '#555cf6',
  SPELL: '#533b9b', POND: '#3763cf', AMP: '#d62e7a', GTC: '#97d8d7', SLP: '#cb7f76', DAR: '#ff6403',
  LOOM: '#1aa5bc', IDEX: '#672cc9', C98: '#e0bf54', BADGER: '#df9e36', MLN: '#6f56fd', TRU: '#1b5bff',
  UNFI: '#38f897', SSV: '#1ba5f8', MAV: '#6909ff', OCEAN: '#8a919c', HOOK: '#8a919c', EDU: '#05cfd2',
  LEVER: '#8a919c', BAKE: '#f6bf79', ORDI: '#8a919c', XTZ: '#0063ff', BLUR: '#c04416', PERP: '#38db9f',
  CFX: '#8a919c', ARKM: '#8a919c', WOO: '#8a919c', PROM: '#e98382', RAY: '#6e71f7', FIDA: '#1900d6',
  ARPA: '#8a919c', MDT: '#73b4fc', KEY: '#3ba6f5', PHB: '#005afa', LIT: '#15c18f', WBTC: '#ffa83b',
  USDT: '#26a17b', USDC: '#2775ca', STMX: '#fd2f54', DAI: '#f5ac37', MNT: '#3b9b7d', BETA: '#8a919c',
  TUSD: '#002868', DGB: '#1375d6', VOXEL: '#4184cc', LSK: '#8a919c', XEM: '#a5c970', IOTA: '#0808ff',
  CRO: '#8a919c', '1INCH': '#8a919c', DCR: '#2a71ff', DUSK: '#8a919c', POLY: '#3b559b', ALPHA: '#c86f51',
  BTT: '#8a919c', WIN: '#9b8e3b', LUNC: '#9b8b3b', STEEM: '#2939c7', NULS: '#00e789', DOCK: '#8a919c',
  WAN: '#2186c3', ERN: '#2b68ac', RARE: '#8a919c', BSV: '#ecba15', HOT: '#9244ff',
};

/**
 * A colour is only an identity if you can see it: anything darker than the UI background gets its
 * lightness floored (hue kept). Catches the remaining near-black brands (XRP, Nike, Palantir…)
 * without rewriting their entries.
 */
function visibleColor(hex: string): string {
  if (!hex.startsWith('#') || hex.length !== 7) return hex;
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (l >= 0.18) return hex;
  let h = 0, s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }
  return `hsl(${Math.round(h * 360)}, ${Math.round(s * 100)}%, 32%)`;
}

export function getAssetColor(symbol: string): string {
  return visibleColor(CRYPTO_ICON_COLORS[symbol] || BRAND_COLORS[symbol] || hashColor(symbol));
}

// Logos that are a dark glyph on a transparent background (measured: mean luminance < 60, opaque
// coverage < 85%) — invisible over a dark chip. These render on a light disc instead, the same
// treatment the chart engine's DARK_LOGO set gets (§chart-icons).
const DARK_TRANSPARENT_LOGOS = new Set([
  'ADA', 'ONDO', 'APT', 'WLD', 'AR', 'BAL', 'CVC', 'TLM', 'OCEAN', 'CFX', 'LSK', '1INCH',
]);

/** True when a crypto logo needs a light backing disc to be visible on the dark UI. */
export function needsLightChip(symbol: string, assetType: AssetType): boolean {
  return assetType === 'crypto' && DARK_TRANSPARENT_LOGOS.has(symbol);
}

// ── Stock logos: Google's favicon service, keyed by a hand-curated domain map ──
const STOCK_DOMAINS: Record<string, string> = {
  // ETFs + MSTR — used by the market page's Stocks & ETFs tab. Without a domain here the favicon
  // lookup returns null and the row falls back to a bare letter chip.
  SPY: 'ssga.com', QQQ: 'invesco.com', IWM: 'ishares.com',
  GLD: 'spdrgoldshares.com', MSTR: 'strategy.com',
  AAPL: 'apple.com', MSFT: 'microsoft.com', GOOGL: 'google.com',
  AMZN: 'amazon.com', TSLA: 'tesla.com', META: 'meta.com',
  NVDA: 'nvidia.com', JPM: 'jpmorganchase.com', V: 'visa.com',
  MA: 'mastercard.com', JNJ: 'jnj.com', WMT: 'walmart.com',
  PG: 'pg.com', UNH: 'unitedhealthgroup.com', HD: 'homedepot.com',
  DIS: 'disney.com', NFLX: 'netflix.com', PYPL: 'paypal.com',
  AMD: 'amd.com', INTC: 'intel.com', BA: 'boeing.com',
  GS: 'goldmansachs.com', IBM: 'ibm.com', ORCL: 'oracle.com',
  CRM: 'salesforce.com', ADBE: 'adobe.com', CSCO: 'cisco.com',
  PFE: 'pfizer.com', MRK: 'merck.com', ABBV: 'abbvie.com',
  XOM: 'exxonmobil.com', CVX: 'chevron.com', KO: 'coca-cola.com',
  PEP: 'pepsico.com', MCD: 'mcdonalds.com', NKE: 'nike.com',
  SBUX: 'starbucks.com', T: 'att.com', VZ: 'verizon.com',
  GM: 'gm.com', F: 'ford.com', UBER: 'uber.com',
  SQ: 'squareup.com', COIN: 'coinbase.com', PLTR: 'palantir.com',
  SNAP: 'snap.com', RBLX: 'roblox.com', SHOP: 'shopify.com',
  SPOT: 'spotify.com', ZM: 'zoom.us',
};

// ── Currency → ISO country code, for flag images ──
const CURRENCY_FLAGS: Record<string, string> = {
  EUR: 'eu', GBP: 'gb', JPY: 'jp', MXN: 'mx',
  CAD: 'ca', AUD: 'au', CHF: 'ch', CNY: 'cn',
  BRL: 'br', KRW: 'kr',
};

/** Builds a metallic coin as an inline SVG data-URI — no binary asset needed. */
function metalSvg(
  text: string, light: string, mid: string, dark: string,
  rim: string, textDark: string, textLight: string,
): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><radialGradient id="bg" cx="35%" cy="30%" r="65%"><stop offset="0%" stop-color="${light}"/><stop offset="40%" stop-color="${mid}"/><stop offset="100%" stop-color="${dark}"/></radialGradient><linearGradient id="rim" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${light}"/><stop offset="50%" stop-color="${rim}"/><stop offset="100%" stop-color="${light}"/></linearGradient><radialGradient id="sh" cx="30%" cy="25%" r="35%"><stop offset="0%" stop-color="white" stop-opacity="0.55"/><stop offset="100%" stop-color="white" stop-opacity="0"/></radialGradient></defs><circle cx="50" cy="50" r="48" fill="url(#bg)"/><circle cx="50" cy="50" r="46" fill="none" stroke="url(#rim)" stroke-width="2"/><circle cx="50" cy="50" r="40" fill="none" stroke="${rim}" stroke-width="0.5" opacity="0.25"/><circle cx="44" cy="40" r="28" fill="url(#sh)"/><text x="50" y="57" text-anchor="middle" font-size="26" font-weight="700" fill="${textLight}" font-family="system-ui,sans-serif" letter-spacing="1" opacity="0.35">${text}</text><text x="50" y="58" text-anchor="middle" font-size="26" font-weight="700" fill="${textDark}" font-family="system-ui,sans-serif" letter-spacing="1">${text}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

/* Inline-SVG coins — the fallback if a .gif ever fails to load. */
const METAL_SVGS: Record<string, string> = {
  XAU: metalSvg('Au', '#fff0a0', '#ffd700', '#b8860b', '#c9a840', '#7a5c00', '#fff8dc'),
  XAG: metalSvg('Ag', '#f8f8f8', '#c0c0c0', '#606060', '#909090', '#383838', '#e8e8e8'),
  XPT: metalSvg('Pt', '#ffffff', '#c8ccd8', '#2e3448', '#7880a0', '#1a2038', '#f0f2ff'),
  XPD: metalSvg('Pd', '#e4e8f0', '#a8b0c0', '#485060', '#687888', '#303848', '#d0d4e0'),
};

/* Reach's animated coin sprites. 32×32, ~7KB for all four. */
const METAL_LOGOS: Record<string, string> = {
  XAU: '/metals/gold.gif',
  XAG: '/metals/silver.gif',
  XPT: '/metals/platinum.gif',
  XPD: '/metals/palladium.gif',
};

// CoinCap keys its icons by asset id, not ticker — override the ones that differ.
const COINCAP_ID_MAP: Record<string, string> = {
  MATIC: 'matic-network', SEI: 'sei-network', BNB: 'binance-coin', SHIB: 'shiba-inu',
  NEAR: 'near-protocol', ICP: 'internet-computer', APT: 'aptos', ARB: 'arbitrum',
  OP: 'optimism', INJ: 'injective-protocol', IMX: 'immutable-x', STX: 'stacks',
  GRT: 'the-graph', RNDR: 'render-token', FET: 'fetch', TON: 'toncoin',
  PEPE: 'pepe', KAS: 'kaspa', SUI: 'sui', BAT: 'basic-attention-token',
  SAND: 'the-sandbox', MANA: 'decentraland', AXS: 'axie-infinity', LDO: 'lido-dao',
  ONE: 'harmony', APE: 'apecoin', RUNE: 'thorchain', CAKE: 'pancakeswap',
  JASMY: 'jasmycoin', EGLD: 'elrond', FLOKI: 'floki-inu', BCH: 'bitcoin-cash',
  ETC: 'ethereum-classic', HBAR: 'hedera-hashgraph', SNX: 'synthetix-network-token',
  HOT: 'holo', PAXG: 'pax-gold', OCEAN: 'ocean-protocol', WOO: 'woo-network',
  VET: 'vechain', FTM: 'fantom', YFI: 'yearn-finance', SUSHI: 'sushi',
  OMG: 'omisego', SC: 'siacoin', ZEN: 'zencash', AR: 'arweave',
  TAO: 'bittensor', WLD: 'worldcoin', RVN: 'ravencoin', FLUX: 'zelcash',
  RPL: 'rocket-pool', FXS: 'frax-share', SLP: 'smooth-love-potion', DYDX: 'dydx',
  CFX: 'conflux-network', CRV: 'curve-dao-token', MKR: 'maker', LRC: 'loopring',
  XTZ: 'tezos', BONK: 'bonk', JUP: 'jupiter',
};

// ── Crypto logos: CoinMarketCap's static CDN, keyed by CMC numeric id ──
//
// CoinCap's icon CDN (the previous primary) 404s on 46 of the 203 cataloged coins — anything whose
// CoinCap id never matched its ticker plus everything listed after CoinCap stopped adding icons
// (NEAR, HBAR, ARB, OP, APT, SUI-era and newer). CMC's s2 CDN is the same source the chart engine's
// watchlist icons use (see api/market/coinlogos) and covers every cataloged coin.
//
// Ids are pinned per symbol rather than fetched because the catalog is static: ambiguous tickers
// (TON, ALPHA, GMT…) collide with unrelated higher-cap claimants in a live listing, and rebranded
// projects (Toncoin→Gram, Frax Share→FRAX, Fantom→Sonic) drop out of it entirely. Every id below
// was resolved against CMC's full coin map by catalog *name*, and every logo URL verified 200.
const CMC_LOGO_IDS: Record<string, number> = {
  ETH: 1027, BTC: 1, SOL: 5426, XRP: 52, TRX: 1958, ADA: 2010,
  DOGE: 74, LINK: 1975, BNB: 1839, XLM: 512, LTC: 2, AVAX: 5805,
  DOT: 6636, UNI: 7083, ATOM: 3794, FIL: 2280, ETC: 1321, ICP: 8916,
  MATIC: 3890, VET: 3077, ALGO: 4030, QNT: 3155, AAVE: 7278, HBAR: 4642,
  NEAR: 6535, CHZ: 4066, STX: 4847, ARB: 11841, INJ: 7226, CRV: 6538,
  GRT: 6719, MKR: 1518, IMX: 10603, OP: 11840, SUI: 20947, PEPE: 24478,
  TON: 11419, ONDO: 21159, APT: 21794, BONK: 23095, WLD: 13502, THETA: 2416,
  SHIB: 5994, PENGU: 34466, ENJ: 2130, KAS: 20396, FLOKI: 10804, SEI: 23149,
  TAO: 22974, ZEC: 1437, BAT: 1697, DASH: 131, XMR: 328, WAVES: 1274,
  NEO: 1376, ZIL: 2469, SAND: 6210, MANA: 1966, COMP: 5692, JUP: 29210,
  SNX: 2586, FET: 3773, ONT: 2566, ZRX: 1896, ONE: 3945, KNC: 9444,
  RNDR: 5690, BAND: 4679, STORJ: 1772, NMR: 1732, LRC: 1934, OXT: 5026,
  SKL: 5691, ANKR: 3783, RSR: 3964, AXS: 6783, GALA: 7080, IOST: 2405,
  APE: 18876, GMT: 18069, ICX: 2099, OMG: 1808, CELO: 5567, SC: 1042,
  QTUM: 1684, DYDX: 28324, ZEN: 1698, MASK: 8536, FLOW: 4558, MINA: 8646,
  ROSE: 7653, RUNE: 4157, EOS: 1765, JASMY: 8425, CAKE: 7186, IOTX: 2777,
  AUDIO: 7455, KAVA: 4846, AR: 5632, SXP: 4279, BAL: 5728, EGLD: 6892,
  YFI: 5864, SUSHI: 6758, LDO: 8000, BNT: 1727, UMA: 5617, REN: 2539,
  FTM: 3513, FUN: 1757, RPL: 2943, ACH: 6958, MTL: 1788, DENT: 1886,
  REQ: 2071, CELR: 3814, RLC: 1637, SYS: 541, BLZ: 2505, ALICE: 8766,
  SUPER: 8290, LINA: 7102, CVC: 1816, NKN: 2780, CTSI: 5444, TLM: 9119,
  COTI: 3992, OGN: 5117, FLUX: 3029, FXS: 6953, RVN: 2577, AGLD: 11568,
  PEOPLE: 14806, BCH: 1831, HIGH: 11232, XVS: 7288, PAXG: 4705, RAD: 6843,
  SPELL: 11289, POND: 7497, AMP: 6945, GTC: 10052, SLP: 5824, DAR: 11374,
  LOOM: 2588, IDEX: 3928, C98: 10903, BADGER: 7859, MLN: 1552, TRU: 7725,
  UNFI: 7672, SSV: 12999, MAV: 18037, OCEAN: 3911, HOOK: 22764, EDU: 24613,
  LEVER: 20873, BAKE: 7064, ORDI: 25028, XTZ: 2011, BLUR: 23121, PERP: 6950,
  CFX: 7334, ARKM: 27565, WOO: 7501, PROM: 4120, RAY: 8526, FIDA: 7978,
  ARPA: 4039, MDT: 2348, KEY: 2398, PHB: 13969, LIT: 6833, WBTC: 3717,
  USDT: 825, USDC: 3408, STMX: 2297, DAI: 4943, MNT: 27075, BETA: 11307,
  TUSD: 2563, DGB: 109, VOXEL: 15678, LSK: 1214, XEM: 873, IOTA: 1720,
  CRO: 3635, '1INCH': 8104, DCR: 1168, DUSK: 4092, POLY: 2496, ALPHA: 7232,
  BTT: 16086, WIN: 4206, LUNC: 4172, STEEM: 1230, NULS: 2092, DOCK: 2675,
  WAN: 2606, ERN: 37508, RARE: 11294, BSV: 3602, HOT: 2682,
};

/** True when the logo is a real image that should not sit on a coloured chip (flags, metal coins). */
export function hasLogoOverride(symbol: string, assetType: AssetType): boolean {
  if (assetType === 'metal') return !!METAL_LOGOS[symbol] || !!METAL_SVGS[symbol];
  if (assetType === 'currency') return !!CURRENCY_FLAGS[symbol];
  return false;
}

export function getLogoUrl(symbol: string, assetType: AssetType): string | null {
  if (assetType === 'crypto') {
    const cmcId = CMC_LOGO_IDS[symbol];
    if (cmcId) return `https://s2.coinmarketcap.com/static/img/coins/64x64/${cmcId}.png`;
    // Uncataloged symbol — the old CoinCap chain is still the best blind guess.
    const id = COINCAP_ID_MAP[symbol] || symbol.toLowerCase();
    return `https://assets.coincap.io/assets/icons/${id}@2x.png`;
  }
  if (assetType === 'stock') {
    const domain = STOCK_DOMAINS[symbol];
    return domain ? `https://www.google.com/s2/favicons?domain=${domain}&sz=128` : null;
  }
  if (assetType === 'metal') return METAL_LOGOS[symbol] || METAL_SVGS[symbol] || null;
  if (assetType === 'currency') {
    const code = CURRENCY_FLAGS[symbol];
    return code ? `https://flagcdn.com/w80/${code}.png` : null;
  }
  return null;
}

/** The inline-SVG coin for a metal — used if its .gif fails to load. */
export function getMetalFallbackUrl(symbol: string): string | null {
  return METAL_SVGS[symbol] || null;
}

/** Secondary CDN, tried once when the CoinCap icon 404s. */
export function getCryptoFallbackUrl(symbol: string): string {
  return `https://cdn.jsdelivr.net/npm/cryptocurrency-icons@latest/svg/color/${symbol.toLowerCase()}.svg`;
}

// ── Fallback glyph, shown on a coloured chip when no logo loads ──
const ICON_CHARS: Record<string, string> = {
  BTC: '₿', ETH: 'Ξ',
  XAU: 'Au', XAG: 'Ag', XPT: 'Pt', XPD: 'Pd',
  EUR: '€', GBP: '£', JPY: '¥', MXN: '$',
  CAD: 'C$', AUD: 'A$', CHF: 'Fr', CNY: '¥', BRL: 'R$', KRW: '₩',
};

export function getIconChar(symbol: string): string {
  return ICON_CHARS[symbol] || symbol.charAt(0);
}

// ── Catalogs ──

const CRYPTO_RAW: [string, string][] = [
  ['BTC', 'Bitcoin'], ['ETH', 'Ethereum'], ['BNB', 'BNB'], ['XRP', 'XRP'],
  ['SOL', 'Solana'], ['DOGE', 'Dogecoin'], ['ADA', 'Cardano'], ['TRX', 'TRON'],
  ['LINK', 'Chainlink'], ['XLM', 'Stellar'], ['LTC', 'Litecoin'], ['AVAX', 'Avalanche'],
  ['SHIB', 'Shiba Inu'], ['DOT', 'Polkadot'], ['UNI', 'Uniswap'], ['ATOM', 'Cosmos'],
  ['NEAR', 'NEAR Protocol'], ['ETC', 'Ethereum Classic'], ['ICP', 'Internet Computer'], ['FIL', 'Filecoin'],
  ['HBAR', 'Hedera'], ['APT', 'Aptos'], ['ARB', 'Arbitrum'], ['OP', 'Optimism'],
  ['MATIC', 'Polygon'], ['VET', 'VeChain'], ['ALGO', 'Algorand'], ['QNT', 'Quant'], ['AAVE', 'Aave'],
  ['INJ', 'Injective'], ['IMX', 'Immutable'], ['STX', 'Stacks'], ['CHZ', 'Chiliz'],
  ['CRV', 'Curve DAO'], ['MKR', 'Maker'], ['GRT', 'The Graph'], ['RNDR', 'Render'],
  ['FET', 'Fetch.ai'], ['SUI', 'Sui'], ['TON', 'Toncoin'], ['PEPE', 'Pepe'],
  ['WLD', 'Worldcoin'], ['ONDO', 'Ondo'], ['SEI', 'Sei'], ['JUP', 'Jupiter'],
  ['BONK', 'Bonk'], ['KAS', 'Kaspa'], ['THETA', 'Theta'], ['TAO', 'Bittensor'],
  ['FLOKI', 'Floki'], ['PENGU', 'Pudgy Penguins'],
  ['ENJ', 'Enjin'], ['BAT', 'Basic Attention Token'], ['ZEC', 'Zcash'], ['XMR', 'Monero'],
  ['DASH', 'Dash'], ['NEO', 'Neo'], ['WAVES', 'Waves'], ['ZIL', 'Zilliqa'],
  ['SAND', 'The Sandbox'], ['MANA', 'Decentraland'], ['AXS', 'Axie Infinity'], ['COMP', 'Compound'],
  ['SNX', 'Synthetix'], ['LDO', 'Lido DAO'], ['ONE', 'Harmony'], ['ONT', 'Ontology'],
  ['ZRX', '0x'], ['KNC', 'Kyber Network'], ['BAND', 'Band Protocol'], ['LRC', 'Loopring'],
  ['STORJ', 'Storj'], ['NMR', 'Numeraire'], ['OXT', 'Orchid'], ['SKL', 'SKALE'],
  ['ANKR', 'Ankr'], ['RSR', 'Reserve Rights'], ['GALA', 'Gala'], ['APE', 'ApeCoin'],
  ['GMT', 'GMT'], ['OMG', 'OMG Network'], ['IOST', 'IOST'], ['QTUM', 'Qtum'],
  ['ICX', 'ICON'], ['SC', 'Siacoin'], ['ZEN', 'Horizen'], ['CELO', 'Celo'],
  ['RUNE', 'THORChain'], ['CAKE', 'PancakeSwap'], ['DYDX', 'dYdX'], ['JASMY', 'JasmyCoin'],
  ['MASK', 'Mask Network'], ['FLOW', 'Flow'], ['MINA', 'Mina'], ['ROSE', 'Oasis'],
  ['EGLD', 'MultiversX'], ['IOTX', 'IoTeX'], ['AR', 'Arweave'], ['AUDIO', 'Audius'],
  ['EOS', 'EOS'], ['KAVA', 'Kava'],
  ['FTM', 'Fantom'], ['SXP', 'Solar'], ['YFI', 'Yearn.finance'], ['SUSHI', 'SushiSwap'],
  ['UMA', 'UMA'], ['BAL', 'Balancer'], ['FXS', 'Frax Share'], ['RPL', 'Rocket Pool'],
  ['ACH', 'Alchemy Pay'], ['BNT', 'Bancor'], ['REN', 'Ren'], ['REQ', 'Request'],
  ['FUN', 'FUNToken'], ['HOT', 'Holo'], ['MTL', 'Metal'], ['CELR', 'Celer'],
  ['DENT', 'Dent'], ['SYS', 'Syscoin'], ['BLZ', 'Bluzelle'], ['CVC', 'Civic'],
  ['NKN', 'NKN'], ['RLC', 'iExec'], ['CTSI', 'Cartesi'], ['ALICE', 'MyNeighborAlice'],
  ['TLM', 'Alien Worlds'], ['SUPER', 'SuperVerse'], ['PEOPLE', 'ConstitutionDAO'], ['LINA', 'Linear'],
  ['RVN', 'Ravencoin'], ['FLUX', 'Flux'], ['COTI', 'COTI'], ['OGN', 'Origin'],
  ['SLP', 'Smooth Love Potion'], ['C98', 'Coin98'], ['AGLD', 'Adventure Gold'], ['HIGH', 'Highstreet'],
  ['DAR', 'Mines of Dalarnia'], ['BCH', 'Bitcoin Cash'], ['PAXG', 'PAX Gold'], ['XVS', 'Venus'],
  ['RAD', 'Radicle'], ['SPELL', 'Spell Token'], ['POND', 'Marlin'], ['AMP', 'Amp'],
  ['GTC', 'Gitcoin'], ['IDEX', 'IDEX'], ['BADGER', 'Badger DAO'], ['MLN', 'Enzyme'],
  ['OCEAN', 'Ocean Protocol'], ['LOOM', 'Loom Network'],
  ['SSV', 'SSV Network'], ['EDU', 'Open Campus'], ['HOOK', 'Hooked Protocol'], ['MAV', 'Maverick'],
  ['TRU', 'TrueFi'], ['LEVER', 'LeverFi'], ['UNFI', 'Unifi Protocol'], ['BAKE', 'BakeryToken'],
  ['XTZ', 'Tezos'], ['BLUR', 'Blur'], ['WOO', 'WOO Network'], ['ARKM', 'Arkham'],
  ['ORDI', 'ORDI'], ['CFX', 'Conflux'], ['PERP', 'Perpetual Protocol'], ['RAY', 'Raydium'],
  ['FIDA', 'Bonfida'], ['MDT', 'Measurable Data'], ['KEY', 'SelfKey'], ['PROM', 'Prom'],
  ['BETA', 'Beta Finance'], ['PHB', 'Phoenix'], ['VOXEL', 'Voxies'], ['LIT', 'Litentry'],
  ['ARPA', 'ARPA'], ['STMX', 'StormX'], ['IOTA', 'IOTA'], ['LUNC', 'Terra Classic'],
  ['WBTC', 'Wrapped Bitcoin'], ['USDT', 'Tether'], ['USDC', 'USD Coin'], ['DAI', 'Dai'],
  ['MNT', 'Mantle'], ['CRO', 'Cronos'], ['TUSD', 'TrueUSD'], ['DGB', 'DigiByte'],
  ['DCR', 'Decred'], ['LSK', 'Lisk'], ['POLY', 'Polymath'], ['XEM', 'NEM'],
  ['BTT', 'BitTorrent'], ['WIN', 'WINkLink'], ['1INCH', '1inch'],
  ['ALPHA', 'Alpha Venture DAO'], ['DUSK', 'Dusk'], ['NULS', 'NULS'],
  ['STEEM', 'Steem'], ['WAN', 'Wanchain'], ['DOCK', 'Dock'],
  ['ERN', 'Ethernity'], ['RARE', 'SuperRare'], ['BSV', 'Bitcoin SV'],
];

const STOCK_RAW: [string, string][] = [
  ['AAPL', 'Apple'], ['MSFT', 'Microsoft'], ['GOOGL', 'Alphabet'], ['AMZN', 'Amazon'],
  ['TSLA', 'Tesla'], ['META', 'Meta'], ['NVDA', 'NVIDIA'], ['JPM', 'JPMorgan Chase'],
  ['V', 'Visa'], ['MA', 'Mastercard'], ['JNJ', 'Johnson & Johnson'], ['WMT', 'Walmart'],
  ['PG', 'Procter & Gamble'], ['UNH', 'UnitedHealth'], ['HD', 'Home Depot'], ['DIS', 'Disney'],
  ['NFLX', 'Netflix'], ['PYPL', 'PayPal'], ['AMD', 'AMD'], ['INTC', 'Intel'],
  ['BA', 'Boeing'], ['GS', 'Goldman Sachs'], ['IBM', 'IBM'], ['ORCL', 'Oracle'],
  ['CRM', 'Salesforce'], ['ADBE', 'Adobe'], ['CSCO', 'Cisco'], ['PFE', 'Pfizer'],
  ['MRK', 'Merck'], ['ABBV', 'AbbVie'], ['XOM', 'ExxonMobil'], ['CVX', 'Chevron'],
  ['KO', 'Coca-Cola'], ['PEP', 'PepsiCo'], ['MCD', "McDonald's"], ['NKE', 'Nike'],
  ['SBUX', 'Starbucks'], ['T', 'AT&T'], ['VZ', 'Verizon'], ['GM', 'General Motors'],
  ['F', 'Ford'], ['UBER', 'Uber'], ['SQ', 'Block'], ['COIN', 'Coinbase'],
  ['PLTR', 'Palantir'], ['SNAP', 'Snap'], ['RBLX', 'Roblox'], ['SHOP', 'Shopify'],
  ['SPOT', 'Spotify'], ['ZM', 'Zoom'],
];

export const METAL_LIST: CatalogAsset[] = [
  { symbol: 'XAU', name: 'Gold' },
  { symbol: 'XAG', name: 'Silver' },
  { symbol: 'XPT', name: 'Platinum' },
  { symbol: 'XPD', name: 'Palladium' },
];

export const CURRENCY_LIST: CatalogAsset[] = [
  { symbol: 'EUR', name: 'Euro' },
  { symbol: 'GBP', name: 'British Pound' },
  { symbol: 'JPY', name: 'Japanese Yen' },
  { symbol: 'MXN', name: 'Mexican Peso' },
  { symbol: 'CAD', name: 'Canadian Dollar' },
  { symbol: 'AUD', name: 'Australian Dollar' },
  { symbol: 'CHF', name: 'Swiss Franc' },
  { symbol: 'CNY', name: 'Chinese Yuan' },
  { symbol: 'BRL', name: 'Brazilian Real' },
  { symbol: 'KRW', name: 'Korean Won' },
];

export const ASSET_CATALOG: Record<AssetType, CatalogAsset[]> = {
  crypto: CRYPTO_RAW.map(([symbol, name]) => ({ symbol, name })),
  stock: STOCK_RAW.map(([symbol, name]) => ({ symbol, name })),
  metal: METAL_LIST,
  currency: CURRENCY_LIST,
};

export const TYPE_TABS: { id: AssetType; label: string }[] = [
  { id: 'crypto', label: 'Crypto' },
  { id: 'stock', label: 'Stocks' },
  { id: 'metal', label: 'Metals' },
  { id: 'currency', label: 'Currencies' },
];

/** Looks up an asset's display name; falls back to the symbol for anything not cataloged. */
export function getAssetName(symbol: string, assetType: AssetType): string {
  return ASSET_CATALOG[assetType]?.find((a) => a.symbol === symbol)?.name || symbol;
}

// ── Shared formatters (Reach defines these per-component; centralised here) ──

/** Absolute USD — callers prepend their own sign, matching Reach. */
export function fmtUsd(v: number, d = 2): string {
  return (
    '$' +
    Math.abs(v).toLocaleString(undefined, { minimumFractionDigits: d, maximumFractionDigits: d })
  );
}

/** Price, widening to 8 decimals for sub-$1 assets so micro-caps don't all read $0.00. */
export function fmtPrice(p: number): string {
  return (
    '$' + p.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: p < 1 ? 8 : 2 })
  );
}
