// The analysis layer — turns the ranked data into readable commentary.
//
// ── What this model can and cannot know ──
//
// It is handed numbers and nothing else: price, percent change, 24h volume, market cap, CMC rank,
// turnover, and a sentiment snapshot. It has no news feed, no filings, no X/Twitter (there's no free
// read tier — see sentiment/x.ts for where that would slot in).
//
// That makes the honest ceiling on this analysis *structural*, not causal. It can say "MOVER rose
// 18% on volume worth 40% of its market cap, while Fear & Greed sat at 62" — a real, checkable
// observation. It cannot say *why*, because nothing in its input contains a reason.
//
// An LLM asked "why did this go up?" with no causal data will happily invent a partnership or an
// ETF rumour, and it will sound authoritative. That failure mode is the single biggest risk in this
// feature: a fabricated catalyst is worse than silence, because someone might trade on it. So:
//
//   1. The prompt forbids invented causes and mandates the exact phrase "no clear catalyst
//      identified" when the cause is unknown (which is, honestly, almost always).
//   2. The prompt forbids buy/sell/hold calls and price targets.
//   3. A disclaimer is required, and validateAnalysis() REJECTS the response if it's missing —
//      the one rule enforced in code rather than merely requested.
//
// Rules 1-2 are requests a model can ignore; rule 3 is a guarantee. Documented in ARCHITECTURE.md
// as a known limitation rather than papered over.
//
// ── Providers ──
// Gemini Flash free tier is primary; Groq's llama-3.1-8b-instant is the fallback, and per the
// product decision it is tried ONLY on a 429 (quota exhaustion). Any other Gemini failure yields a
// null analysis instead of silently swapping providers, so a persistent fault stays visible rather
// than hiding behind a fallback that quietly changes the voice of the report.

import type { LlmAnalysis, Period, RankedCoin, RankedPair, Sentiment } from './types';

// `-latest` tracks the current stable Flash model rather than pinning a version that eventually
// gets retired out from under the cron.
const GEMINI_MODEL = 'gemini-flash-latest';
const GROQ_MODEL = 'llama-3.1-8b-instant';
const LLM_TIMEOUT_MS = 30_000;

/** Base URLs, overridable so the analysis path can be exercised against a local mock without
 *  burning real quota (or needing a key). Unset in production → the real endpoints. */
const GEMINI_BASE =
  process.env.GEMINI_BASE_URL ?? 'https://generativelanguage.googleapis.com/v1beta';
const GROQ_BASE = process.env.GROQ_BASE_URL ?? 'https://api.groq.com/openai/v1';

/** Required verbatim on every report. Enforced in code, not left to the model's goodwill. */
export const REQUIRED_DISCLAIMER =
  'This report is generated by an AI model from public market data for informational purposes only. ' +
  'It is not financial advice. Cryptocurrency markets are highly volatile; verify all data ' +
  'independently before making decisions.';

const PERIOD_WINDOW: Record<Period, string> = {
  daily: 'the last 24 hours',
  weekly: 'the last 7 days',
  monthly: 'the last 30 days',
};

/** Thrown so the caller can distinguish "out of quota" (fall back) from "broken" (don't). */
class RateLimitError extends Error {}

function buildPrompt(
  period: Period,
  coins: RankedCoin[],
  pairs: RankedPair[],
  sentiment: Sentiment,
): string {
  // Only the fields the model may reason from — deliberately no free-text so there's nothing to
  // mistake for a news headline.
  const payload = {
    period,
    window: PERIOD_WINDOW[period],
    topGainersCoinMarketCap: coins.map((c) => ({
      symbol: c.symbol,
      name: c.name,
      changePct: Number(c.changePct.toFixed(2)),
      price: c.price,
      volume24hUsd: Math.round(c.volume),
      marketCapUsd: Math.round(c.marketCap),
      cmcRank: c.cmcRank,
      volumeToMarketCapRatio: Number(c.turnover.toFixed(3)),
    })),
    topGainersBinanceUsdtPairs: pairs.map((p) => ({
      symbol: p.symbol,
      changePct: Number(p.changePct.toFixed(2)),
      lastPrice: p.lastPrice,
      quoteVolume24hUsdt: Math.round(p.quoteVolume),
    })),
    sentiment: {
      fearGreedIndex: sentiment.fearGreed,
      trendingOnCoinMarketCap: sentiment.trending.slice(0, 15),
      mostVisitedOnCoinMarketCap: sentiment.mostVisited.slice(0, 15),
      recentlyAddedToCoinMarketCap: sentiment.recentlyAdded.slice(0, 15),
    },
  };

  return `You are a market-data summarizer. You are NOT a financial advisor.

Below is JSON describing the top cryptocurrency gainers over ${PERIOD_WINDOW[period]}, plus market sentiment indicators.

${JSON.stringify(payload, null, 2)}

Write a JSON analysis with EXACTLY this shape:
{
  "summary": string,        // 2-4 sentences on the overall market read for this period
  "coinTheses": [ { "symbol": string, "thesis": string } ],  // one per CoinMarketCap coin above, same symbols, 1-2 sentences each
  "riskFlags": string[],    // 2-5 concrete risks visible IN THIS DATA
  "disclaimer": string
}

HARD RULES — these are not stylistic preferences:

1. The JSON above is the ONLY information you have. You have no news feed, no social media, no
   announcements, no knowledge of events. Do not use anything you think you remember about these
   tokens from training — it is stale and may be wrong.

2. NEVER invent a reason for a price move. Do not mention partnerships, listings, ETFs, hacks,
   upgrades, burns, unlocks, or any event — none of that is in your input, so any such claim is
   fabricated. When you cannot explain a move from the numbers alone (this will be almost every
   coin), use the exact phrase "no clear catalyst identified" in that coin's thesis.

3. What you CAN legitimately say, because it is in the data: the size of the move, the volume
   relative to market cap (high turnover = unusually active trading), the market-cap tier and rank
   (a lower rank means a thinner, more volatile asset), whether the coin also appears in the
   trending/most-visited lists (crowd attention), and how it sits against the Fear & Greed reading.

4. NEVER give a buy/sell/hold recommendation, a price target, or a prediction. Describe what the
   data shows; do not tell the reader what to do or what happens next.

5. "disclaimer" must be set to EXACTLY this string, character for character:
${REQUIRED_DISCLAIMER}

6. Output ONLY the JSON object. No markdown fences, no prose before or after.`;
}

/** Accept only a well-formed analysis carrying the required disclaimer; anything else is a failure. */
function validateAnalysis(raw: unknown, coins: RankedCoin[]): LlmAnalysis | null {
  if (!raw || typeof raw !== 'object') return null;
  const o = raw as Record<string, unknown>;

  const summary = typeof o.summary === 'string' ? o.summary.trim() : '';
  if (!summary) return null;

  // The one rule enforced rather than requested. A model that drops the disclaimer doesn't get to
  // publish; we'd rather show data with no analysis than analysis with no disclaimer.
  if (typeof o.disclaimer !== 'string' || !o.disclaimer.trim()) return null;

  const known = new Set(coins.map((c) => c.symbol));
  const coinTheses = Array.isArray(o.coinTheses)
    ? o.coinTheses
        .map((t) => {
          const e = t as Record<string, unknown>;
          return {
            symbol: typeof e?.symbol === 'string' ? e.symbol : '',
            thesis: typeof e?.thesis === 'string' ? e.thesis.trim() : '',
          };
        })
        // Drop theses for coins that aren't in the report — a hallucinated symbol has no row to
        // attach to, and rendering it would imply we ranked something we didn't.
        .filter((t) => t.symbol && t.thesis && known.has(t.symbol))
    : [];

  const riskFlags = Array.isArray(o.riskFlags)
    ? o.riskFlags.filter((r): r is string => typeof r === 'string' && r.trim().length > 0)
    : [];

  return {
    summary,
    coinTheses,
    riskFlags,
    // Always store our canonical text, never the model's echo of it — that way a subtly reworded
    // disclaimer can't reach the page.
    disclaimer: REQUIRED_DISCLAIMER,
  };
}

/** Strip ```json fences if the model adds them despite being told not to. */
function parseJsonLoose(text: string): unknown {
  const trimmed = text.trim().replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '');
  try {
    return JSON.parse(trimmed);
  } catch {
    // Last resort: the outermost {...} span.
    const start = trimmed.indexOf('{');
    const end = trimmed.lastIndexOf('}');
    if (start === -1 || end <= start) return null;
    try {
      return JSON.parse(trimmed.slice(start, end + 1));
    } catch {
      return null;
    }
  }
}

async function callGemini(prompt: string, apiKey: string): Promise<unknown> {
  const res = await fetch(
    `${GEMINI_BASE}/models/${GEMINI_MODEL}:generateContent`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-goog-api-key': apiKey },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { responseMimeType: 'application/json', temperature: 0.4 },
      }),
      signal: AbortSignal.timeout(LLM_TIMEOUT_MS),
      cache: 'no-store',
    },
  );
  if (res.status === 429) throw new RateLimitError('gemini 429');
  if (!res.ok) throw new Error(`gemini HTTP ${res.status}`);
  const d = (await res.json()) as {
    candidates?: { content?: { parts?: { text?: string }[] } }[];
  };
  const text = d?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('gemini: empty response');
  return parseJsonLoose(text);
}

async function callGroq(prompt: string, apiKey: string): Promise<unknown> {
  const res = await fetch(`${GROQ_BASE}/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: GROQ_MODEL,
      messages: [{ role: 'user', content: prompt }],
      response_format: { type: 'json_object' },
      temperature: 0.4,
    }),
    signal: AbortSignal.timeout(LLM_TIMEOUT_MS),
    cache: 'no-store',
  });
  if (!res.ok) throw new Error(`groq HTTP ${res.status}`);
  const d = (await res.json()) as { choices?: { message?: { content?: string } }[] };
  const text = d?.choices?.[0]?.message?.content;
  if (!text) throw new Error('groq: empty response');
  return parseJsonLoose(text);
}

/**
 * Analysis for a report, or `{ analysis: null }` if it can't be produced honestly.
 *
 * Never throws: a report without analysis is a fine report; a report that fails to save because the
 * LLM was down is not.
 */
export async function analyze(
  period: Period,
  coins: RankedCoin[],
  pairs: RankedPair[],
  sentiment: Sentiment,
): Promise<{ analysis: LlmAnalysis | null; provider: string | null }> {
  // Nothing ranked → nothing to analyze. Don't spend quota to have a model describe an empty list.
  if (coins.length === 0) return { analysis: null, provider: null };

  const geminiKey = process.env.GEMINI_API_KEY;
  const groqKey = process.env.GROQ_API_KEY;
  if (!geminiKey && !groqKey) return { analysis: null, provider: null };

  const prompt = buildPrompt(period, coins, pairs, sentiment);

  if (geminiKey) {
    try {
      const analysis = validateAnalysis(await callGemini(prompt, geminiKey), coins);
      if (analysis) return { analysis, provider: 'gemini' };
      // Parsed but malformed — fall through to Groq rather than publish a broken shape.
    } catch (e) {
      // Per the product decision: fall back ONLY when the free tier is exhausted. Any other Gemini
      // failure returns null so the fault stays visible instead of being masked.
      if (!(e instanceof RateLimitError)) return { analysis: null, provider: null };
    }
  }

  if (groqKey) {
    try {
      const analysis = validateAnalysis(await callGroq(prompt, groqKey), coins);
      if (analysis) return { analysis, provider: 'groq' };
    } catch {
      // Both providers down — data-only report.
    }
  }

  return { analysis: null, provider: null };
}
